sudo: required
services:
  - docker

before_install:
  - docker build -t ibsanmorales/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ibsanmorales/docker-react npm run test

 deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2"
  bucket_path: "docker"
  on:
    branch: master
  acces_key_id: $AWS_ACCESS_KEY
  secret_access_key:  $AWS_SECRET_KEY